### PR TITLE
feat: Custom step definition

### PR DESCRIPTION
**Pull request by tony-go**
Hi 👋 

This pull request contains the documentation for the custom step definition feature in RestQA.

### CODE REVIEW

**Comment by tony-go** [comment]
@olivierodo I update the content

**Review by olivierodo — APPROVED** [review]
LGTM 👍

**Review by KaTLaz — APPROVED** [review]

**Comment by KaTLaz** [comment]
Reviewed

**Comment by KaTLaz** [comment]
reviewed

**Comment by KaTLaz** [comment]
Reviewed

**Pull request merged**
